### PR TITLE
Mohamed

### PR DESCRIPTION
**Pull request by Mohamedddddddd**
test

### CODE REVIEW

**Comment by mehmetakin12** [comment]
testttt

**Comment by Mohamedddddddd** [comment]
<body background= "http://4.bp.blogspot.com/-7NwKjSn3ywg/UKIQ-e8u9EI/AAAAAAAAI2k/gGPApmBEiD8/s1600/foto-van-een-gigantisch-groot-vuurwerk-spektakel-hd-vuurwerk-wallpaper.jpg">

**Comment by Mohamedddddddd** [comment]
http://4.bp.blogspot.com/-7NwKjSn3ywg/UKIQ-e8u9EI/AAAAAAAAI2k/gGPApmBEiD8/s1600/foto-van-een-gigantisch-groot-vuurwerk-spektakel-hd-vuurwerk-wallpaper.jpg

**Comment by Mohamedddddddd** [comment]
<div class="navbar-right">
                    <form class="navbar-form" method="get" action="/zoeken">
                        <input type="text" class="search-query" placeholder=Zoeken name="query" value="">
                    
				</form>
                </div>

**Comment by Mohamedddddddd** [comment]
<div class="navbar-right">
                    <form class="navbar-form" method="get" action="/zoeken">
                        <input type="text" class="search-query" placeholder=Zoeken name="query" value="">
                    
				</form>
                </div>

**Comment by Mohamedddddddd** [comment]
<div class="navbar-right">
                    <form class="navbar-form" method="get" action="/zoeken">
                        <input type="text" class="search-query" placeholder=Zoeken name="query" value="">
                    
				</form>
                </div>

**Pull request closed without merging**
